##
## Makefile for Makefile in /home/debas_e/Project/System_Unix/PSU_2013_myirc/src/client/my_irc_Qt
## 
## Made by Etienne
## Login   <debas_e@epitech.net>
## 
## Started on  Sat Apr 26 21:11:20 2014 Etienne
## Last update Sat Apr 26 21:47:51 2014 Etienne
##

NAME		= client

CC		= gcc

CXX		= g++

DEFINES       	= -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED

CFLAGS        	= -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)

CXXFLAGS      	= -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)

LFLAGS		= -Wl,-O1

LIBS		= $(SUBLIBS)  -L/usr/lib64 -lQtGui -L/usr/lib64 -L/usr/X11R6/lib -lQtCore -lpthread

INCPATH       	= -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtCore
INCPATH       	+= -I/usr/include/QtGui -I/usr/include -I../includes -I.

SOURCES       	= main.cpp \
		  ircdisplay.cpp \
		  client_manage_msg.c \
		  socket_client.c \
		  connect.c \
		  select_loop.c \
		  str_to_wordtab.c \
		  ring_buff.c

OBJECTS       	= main.o \
		  ircdisplay.o \
		  client_manage_msg.o \
		  socket_client.o \
		  connect.o \
		  select_loop.o \
		  str_to_wordtab.o \
		  ring_buff.o

LINK		= g++

all:	$(NAME)

$(NAME): $(OBJECTS)
	$(LINK) $(LFLAGS) -o $(NAME) $(OBJECTS) $(OBJCOMP) $(LIBS)

main.o: main.cpp ircdisplay.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ircdisplay.o: ircdisplay.cpp ircdisplay.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ircdisplay.o ircdisplay.cpp

client_manage_msg.o: client_manage_msg.c
	$(CC) -c $(CFLAGS) $(INCPATH) -o client_manage_msg.o client_manage_msg.c

socket_client.o: socket_client.c
	$(CC) -c $(CFLAGS) $(INCPATH) -o socket_client.o socket_client.c

connect.o: connect.c
	$(CC) -c $(CFLAGS) $(INCPATH) -o connect.o connect.c

select_loop.o: select_loop.c
	$(CC) -c $(CFLAGS) $(INCPATH) -o select_loop.o select_loop.c

str_to_wordtab.o: str_to_wordtab.c
	$(CC) -c $(CFLAGS) $(INCPATH) -o str_to_wordtab.o str_to_wordtab.c

ring_buff.o: ring_buff.c
	$(CC) -c $(CFLAGS) $(INCPATH) -o ring_buff.o ring_buff.c

